### ISSUE TITLE
SFCGAL fell off Ubuntu Bionic

### ISSUE THREAD

**Issue by Komzpa** [Oslandia/SFCGAL#167]
SFCGAL is absent in Ubuntu Bionic for some reason:
https://launchpad.net/ubuntu/bionic/+source/sfcgal

Likely a build failure:
https://launchpadlibrarian.net/348102632/buildlog_ubuntu-bionic-amd64.sfcgal_1.3.1-2build2_BUILDING.txt.gz

**Comment by mhugo** [comment]
Same error as in #152

Would you have the opportunity to test the new branch https://github.com/Oslandia/SFCGAL/tree/bundled that should fix the problem ?

**Comment by Komzpa** [comment]
@mhugo the most common thing that happens in debian-like distros when someone tries to "bundle" a dependency the packager has to unbundle it back, having double effort.

However @sebastic is the right person to consult about it.

**Comment by sebastic** [comment]
The GIS & OSM packages in Ubuntu are not actively maintained, so no one is likely to provide a [stable update](https://wiki.ubuntu.com/StableReleaseUpdates) to fix sfcgal in Ubuntu. Since postgis would need a rebuild too, it might be a bit too invasive for an SRU.

The FTBFS with CGAL 4.11 was fixed in 1.3.3-1, and the subsequent FTBFS with CGAL 4.12 in 1.3.5-2 & 1.3.5-3. Those were all released after the Debian Import Freeze, so weren't synced from Debian.

sfcgal is not available for bionic in the UbuntuGIS PPA yet either, but could easily be added. But like Ubuntu itself, it requires people to do the work. @kalxas does most of the work these days, but as sfcgal was also not included in the OSGeoLive PPA, it cannot just be copied. Contact the Debian GIS team if you want help with packaging the PostGIS dependenccies for the UbuntuGIS PPA.

**Comment by Komzpa** [comment]
PGDG APT repos already ship SFCGAL for Ubuntu Bionic: https://wiki.postgresql.org/wiki/Apt - it can probably be copied over from there. PostGIS there is build with SFCGAL too.

It's mostly upsetting since Bionic is LTS and you can't safely assume everyone's PostGIS got SFCGAL until year 2023. I've called for a change in PostGIS to make SFCGAL mandatory dependency so this problem doesn't repeat, although problems like #181 make me understand why packaging SFCGAL is so hard it got dropped.

Will building postgis with sfcgal as part of sfcgal build be interesting CI test?

**Comment by sebastic** [comment]
Making sfcgal a hard dependency of postgis will mean that postgis will not be included in Debian & Ubuntu when a scenario like this happens again.

Based on my experience with SFCGAL and its lack of active development (all recent issues were fixed by a CGAL developer), I strongly urge you not to make SFCGAL a required dependency of PostGIS. SFCGAL can only become a hard requirement of PostGIS if PostGIS developers also become SFCGAL developers.

**Comment by mhugo** [comment]
> @mhugo the most common thing that happens in debian-like distros when someone tries to "bundle" a dependency the packager has to unbundle it back, having double effort.

I don't get it. Why unbundle ? The point of the proposition was to ease packager's work.

Anyway, @sloriot lastly added [undocumented parts of CGAL](https://github.com/Oslandia/SFCGAL/tree/master/CGAL_patches/CGAL) that were used in SFCGAL in the source tree. That should be a correct compromise. I'll remove my "bundle" branch.

**Comment by kalxas** [comment]
Please test the new packages for Bionic:
https://lists.osgeo.org/pipermail/ubuntu/2018-November/001789.html
SFCGAL support for PostGIS enabled.

**Comment by Komzpa** [comment]
Seems nothing more can be done about it. Let's keep it compilable :)

**Comment by kalxas** [comment]
SFCGAL is included in UbuntuGIS ppa for Bionic.
